### ISSUE TITLE
question

### ISSUE THREAD

**Issue by smolleyes** [dxhbiz/ntrip-client#7]
hi

thanks for this module, will try but what s this xyz param in the options ? what does it represent since i ve never been asked for it on an ntrip client ? 

anyway to get the list of mountpoints added ? 

thanks

**Comment by dxhbiz** [comment]
@smolleyes 

Sorry for the late reply

1. some ntripcaster service providers, need to distribute base station data stream according to location. So xyz is mainly used to generate GGA data for pulling correction services

2. it seems to get mountpointl list is very necessary, I will add this feature as soon as possible

**Comment by dxhbiz** [comment]
getting the list of mountpoints is complete
