### ISSUE TITLE
Typo in write() function

### ISSUE THREAD

**Issue by yosuke** [dxhbiz/ntrip-client#8]
This line:
https://github.com/dxhbiz/ntrip-client/blob/master/lib/client.js#L116
```
    if (this.close || this.isError) {
      return;
    }
```
Is probably a typo of:
```
    if (this.isClose || this.isError) {
      return;
    }
```
The current `write()` function always return without writing, because `this.close` is always `true`.

**Comment by dxhbiz** [comment]
Thanks

I fixed it.

**Comment by dxhbiz** [comment]
Thanks

I fixed it.
